#!/bin/sh

# bash test/stepik-scraper-iframe-remove.sh ignored/cse100.html ignored/cse100-noiframe.html

sed -e 's/<iframe/<x-iframe/' -e 's/iframe>/x-iframe>/' $1 > "$2"
echo '<script>' >> "$2"
echo "for (const element of document.querySelectorAll('x-iframe')) {" >> "$2"
echo "  Object.assign(element.style, {" >> "$2"
echo "    display: 'flex'," >> "$2"
echo "    flexDirection: 'column'," >> "$2"
echo "    justifyContent: 'center'," >> "$2"
echo "    alignItems: 'center'," >> "$2"
echo "    border: '1px solid black'" >> "$2"
echo "  })" >> "$2"
echo "  element.append(" >> "$2"
echo "    element.getAttribute('src')," >> "$2"
echo "    Object.assign(document.createElement('button'), {" >> "$2"
echo "      textContent: 'View iframe'," >> "$2"
echo "      onclick: function () {" >> "$2"
echo "        this.replaceWith(Object.assign(document.createElement('iframe'), {" >> "$2"
echo "          src: element.getAttribute('src')," >> "$2"
echo "          width: element.getAttribute('width')," >> "$2"
echo "          height: element.getAttribute('height')," >> "$2"
echo "          allowFullscreen: true" >> "$2"
echo "        }))" >> "$2"
echo "      }" >> "$2"
echo "    })" >> "$2"
echo "  )" >> "$2"
echo "}" >> "$2"
echo '</script>' >> "$2"
