export const voices = {
  3: 'Alana B. (Narration)',
  4: 'Ramona J. (Narration)',
  5: 'Ramona J. (Promo)',
  7: 'Wade C. (Narration) [Now ID 30]',
  8: 'Sofia H. (Narration)',
  10: 'Vanessa N. (Narration)',
  11: 'Isabel V. (Narration)',
  12: 'Ava M. (Narration) [Now ID 31]',
  13: 'Jeremy G. (Narration)',
  14: 'Nicole L. (Narration)',
  15: 'Paige L. (Narration)',
  16: 'Tobin A. (Narration)',
  17: 'Kai M. (Narration) [Now ID 32]',
  18: 'Tristan F. (Narration)',
  19: 'Patrick K. (Narration)',
  20: 'Sofia H. (Promo)',
  21: 'Damian P. (Promo)',
  22: 'Jodi P. (Promo)',
  23: 'Lee M. (Promo)',
  24: 'Selene R. (Promo)',
  26: 'Wade C. (Promo)',
  27: 'Joe F. (Narration)',
  28: 'Joe F. (Promo)',
  29: 'Garry J. (Character)',
  30: 'Wade C. (Narration)',
  31: 'Ava M. (Narration)',
  33: 'Jude D. (Narration)',
  32: 'Kai M. (Narration)',
  34: 'Eric S. (Promo)',
  35: 'Chase J. (Narration)',
  37: 'Steve B. (Promo)',
  38: 'Bella B. (Promo)',
  39: 'Tilda C. (Promo)',
  40: 'Charlie Z. (Promo)',
  41: 'Paul B. (Promo)',
  42: 'Sofia H. (Conversational)',
  43: 'Ava M. (Conversational)',
  44: 'Kai M. (Conversational)',
  45: 'Nicole L. (Conversational)',
  46: 'Wade C. (Conversational)',
  47: 'Patrick K. (Conversational)',
  48: 'Vanessa N. (Conversational)',
  49: 'Gia V. (Narration)',
  50: 'Antony A. (Narration)',
  51: 'Jodi P. (Narration)',
  52: 'Raine B. (Narration)',
  53: 'Owen C. (Narration)',
  54: 'Zach E. (Promo)',
  55: 'Genevieve M. (Narration)',
  56: 'Jarvis H. (Narration)',
  57: 'Theo K. (Narration)',
  58: 'James B. (Narration)',
  59: 'Terra G. (Narration)',
  60: 'Philip J. (Narration)',
  61: 'Marcus G. (Narration)',
  62: 'Jordan T. (Narration)',
  63: 'Fiona H. (Narration, UK)',
  65: 'Donna W. (Narration)',
  66: 'Greg G. (Narration)',
  67: 'Zoey O. (Narration)',
  68: 'Kari N. (Narration)',
  69: 'Diarmid C. (Narration)',
  71: 'Alan T. (Narration)',
  72: 'Ava M. (Promo)',
  73: 'Tobin A. (Promo)',
  75: 'Ben D. (Narration)',
  76: 'Michael V. (Narration)',
  77: 'Cameron S. (Narration)',
  78: 'Paula R. (Narration)',
  79: 'Bella B. (Narration)',
  80: 'Marcus G. (Conversational)',
  81: 'Jordan T (Conversational)',
  82: 'Jodi P. (Conversational)',
  83: 'Diarmid C. (Promo)',
  84: 'Jarvis H. (Conversational)',
  85: 'Jarvis H. (Promo)',
  86: 'Gia V. (Conversational)',
  87: 'Gia V. (Promo)',
  88: 'Owen C. (Conversational)',
  89: 'Owen C. (Promo)',
  90: 'Philip J (Conversational)',
  91: 'Genevieve M. (Conversational)',
  92: 'Antony A. (Conversational)',
  93: 'Bella B. (Conversational)',
  94: 'Eric S. (Narration)',
  95: 'Greg G. (Conversational)',
  96: 'Jensen X. (Narration)',
  97: 'Jack C. (Narration)',
  98: 'Oliver S. (Narration)',
  99: 'Hannah A (Narration)',
  100: 'Lorenzo D. (Narration)',
  101: 'Lulu G. (Narration)',
  102: 'Abbi D. (Narration)',
  103: 'Fiona H. (Narration, IE)',
  104: 'Shelby D. (Narration)',
  105: "Se'von M. (Narration)",
  106: 'Jimmy J. (Narration)',
  107: 'Jay S. (Narration)',
  108: 'Selene R. (Narration)',
  109: 'Issa B. (Narration)',
  110: 'Lyric K. (Narration)',
  111: 'Ali P. (Narration)',
  112: 'Aaron G. (Narration)',
  113: 'Jordan T. (Promo)',
  114: 'Greg G. (Promo)',
  115: 'Genevieve M. (Promo)',
  116: 'Marcus G. (Promo)',
  117: 'Nicole L. (Promo)',
  118: 'Philip J. (Promo)',
  119: 'Vanessa N. (Promo)',
  120: 'Diarmid C. (Conversational)',
  121: 'James B. (Conversational)',
  122: 'Lee M. (Conversational)',
  123: 'Tilda C. (Conversational)',
  124: 'Kari N. (Character)',
  125: 'Damian P. (Narration)',
  126: 'Charlie Z. (Narration)',
  127: 'Tilda C. (Narration)',
  128: 'Zach E. (Narration)',
  129: 'Paula R. (Promo)',
  130: 'Alana B. (Conversational)',
  131: 'Paige L. (Conversational)',
  132: 'Fiona H. (Conversational)',
  133: 'Ramona J. (Conversational)',
  135: 'Donna W. (Conversational)',
  136: 'Terra G. (Conversational)',
  137: 'Ben D. (Conversational)',
  138: 'Jeremy G. (Conversational)',
  139: 'Joe F. (Conversational)',
  140: 'Jude D. (Conversational)',
  141: 'Abbi_D (Conversational)',
  142: 'Antony_A (Promotional)',
  143: 'Fiona_H (Promotional)',
  144: 'Hannah_A (Conversational)',
  145: 'Issa_B (Conversational)',
  146: 'Jack_C (Conversational)',
  147: 'Jay_S (Conversational)',
  148: 'Jay_S (Promotional)',
  149: 'Jimmy_J (Conversational)',
  150: 'Lorenzo_D (Conversational)',
  151: 'Lulu_G (Conversational)',
  152: 'Oliver_S (Conversational)',
  153: 'Shelby_D (Conversational)',
  154: 'Shelby_D (Promotional)',
  155: 'Terra_G (Promotional)'
}
