const CACHE_NAME = "test-cache-v01", // change cache name to force update
urlsToCache = [];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(urlsToCache)));
});
self.addEventListener("fetch", e => {
  e.respondWith(caches.match(e.request).then(response => new Response(`<!DOCTYPE html>
<html>
  <head>
    <title>muahahaha</title>
  </head>
  <body>
    <button id="off">unregister service worker</button>
    <p>time stamp: ${Date()}. random number: ${("0" + Math.floor(Math.random() * 100)).slice(-2)}</p>
    <p>th' above paragraph wasn't generated by javascript! ( :O ) use right click &gt; "view page source" to see! (might be different on different browsers)</p>
    <script>
const off = document.getElementById("off");
off.addEventListener("click", e => {
  localStorage.dynamicSW = "off";
  navigator.serviceWorker.getRegistrations().then(regis => regis.map(regis => regis.unregister()));
  window.location.reload();
}, false);
    </script>
  </body>
</html>`, {headers: {"Content-Type": "text/html"}})));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(names => Promise.all(names.map(cache => CACHE_NAME !== cache ? caches.delete(cache) : undefined))));
});
